/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorEsperaLlenadoMesa;
import java.util.ArrayList;
import logica.Jugador;
import logica.Mesa;
import controlador.VistaEsperaLlenadoMesa;
import excepciones.MesaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Mano;

/**
 *
 * @author Agus
 */
public class EsperaLlenadoMesa extends javax.swing.JDialog implements VistaEsperaLlenadoMesa {

    private ControladorEsperaLlenadoMesa controlador;
    /**
     * Creates new form JugarAlPoker
     */
    public EsperaLlenadoMesa(java.awt.Frame parent, boolean modal, Mesa mesa, Jugador jugador) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        controlador = new ControladorEsperaLlenadoMesa(this, mesa, jugador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taMensajes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        taMensajes.setColumns(20);
        taMensajes.setRows(5);
        jScrollPane1.setViewportView(taMensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            controlador.salirMesa();
        } catch (MesaException ex) {
            Logger.getLogger(EsperaLlenadoMesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taMensajes;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void mostrarMensaje(String nombreCompleto, int numeroDeMesa, String mensaje) {
        String titulo = ("JUGADOR " + nombreCompleto.toUpperCase() + " - NUMERO DE MESA: " + numeroDeMesa);
        setTitle(titulo);
        taMensajes.setText(mensaje);
    }
    
    
    @Override
    public void proximoCasoUso(Object resultado, Object resultado2) {
        try {
            Jugador jugador = (Jugador) resultado;
            Mesa mesa = (Mesa) resultado2;
            dispose();
            new JugarAlPoker(null, false, jugador, mesa).setVisible(true);
        } catch (MesaException ex) {
            taMensajes.setText(ex.getMessage());
        }
    }

    @Override
    public void mostrarError(String mensaje) {
        taMensajes.setText(mensaje);        
    }
    
}
