/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorJugarAlPoker;
import controlador.VistaJugarAlPoker;
import excepciones.ManoException;
import excepciones.MesaException;
import excepciones.SaldoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Carta;
import logica.Figura;
import logica.Jugador;
import logica.Mano;
import logica.Mesa;
import panelCartasPoker.CartaPoker;
import panelCartasPoker.PanelCartasListener;
import panelCartasPoker.PanelCartasPokerException;

/**
 *
 * @author Agus
 */
public class JugarAlPoker extends javax.swing.JDialog implements VistaJugarAlPoker, PanelCartasListener{

    private ControladorJugarAlPoker controlador;
    /**
     * Creates new form JugarAlPoker
     */
    public JugarAlPoker(java.awt.Frame parent, boolean modal, Jugador jugador, Mesa mesa) throws MesaException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorJugarAlPoker(this, jugador, mesa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panelCartasPoker = new panelCartasPoker.PanelCartasPoker();
        tfMontoApuesta = new javax.swing.JTextField();
        btnApostar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        labelFigurasPosibles = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFigurasPosibles = new javax.swing.JList();
        labelFiguraActual = new javax.swing.JLabel();
        labelJugadoresEnMesa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaJugadoresEnMesa = new javax.swing.JList();
        labelPozo = new javax.swing.JLabel();
        labelEstadoMano = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taMensajes = new javax.swing.JTextArea();
        btnPasar1 = new javax.swing.JButton();
        btnIGualarApuesta = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tfMontoApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMontoApuestaActionPerformed(evt);
            }
        });

        btnApostar.setText("Apostar");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        btnDescartar.setText("Descartar");
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });

        labelFigurasPosibles.setText("Figuras posibles:");

        jScrollPane2.setViewportView(listaFigurasPosibles);

        labelFiguraActual.setText("Figura actual: ");

        labelJugadoresEnMesa.setText("Jugadores en mesa:");

        jScrollPane3.setViewportView(listaJugadoresEnMesa);

        labelPozo.setText("Pozo:");

        labelEstadoMano.setText("Estado mano:");

        taMensajes.setColumns(20);
        taMensajes.setRows(5);
        jScrollPane4.setViewportView(taMensajes);

        btnPasar1.setText("Pasar");
        btnPasar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasar1ActionPerformed(evt);
            }
        });

        btnIGualarApuesta.setText("Agregar apuesta");
        btnIGualarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIGualarApuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEstadoMano, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356)
                        .addComponent(labelPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelFigurasPosibles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelJugadoresEnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(labelFiguraActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(413, 413, 413)
                                .addComponent(btnPasar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(panelCartasPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tfMontoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(btnIGualarApuesta)
                                            .addGap(7, 7, 7)
                                            .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(511, 511, 511)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoMano)
                    .addComponent(labelPozo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCartasPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFigurasPosibles)
                            .addComponent(labelJugadoresEnMesa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(labelFiguraActual)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIGualarApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMontoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPasar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMontoApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMontoApuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMontoApuestaActionPerformed

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
       
        String valorApuesta = tfMontoApuesta.getText();
        
        try {
            controlador.iniciarApuesta(valorApuesta);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JugarAlPoker.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaldoException ex) {
            Logger.getLogger(JugarAlPoker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            controlador.salirMesa();
        } catch (MesaException ex) {
            Logger.getLogger(JugarAlPoker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnPasar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasar1ActionPerformed
        try {
            controlador.agregarAListaPaso();
        } catch (ManoException ex) {
            Logger.getLogger(JugarAlPoker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPasar1ActionPerformed

    private void btnIGualarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIGualarApuestaActionPerformed
      
        try {
            controlador.ingualarApuesta();
        } catch (SaldoException ex) {
            Logger.getLogger(JugarAlPoker.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIGualarApuestaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnIGualarApuesta;
    private javax.swing.JButton btnPasar1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelEstadoMano;
    private javax.swing.JLabel labelFiguraActual;
    private javax.swing.JLabel labelFigurasPosibles;
    private javax.swing.JLabel labelJugadoresEnMesa;
    private javax.swing.JLabel labelPozo;
    private javax.swing.JList listaFigurasPosibles;
    private javax.swing.JList listaJugadoresEnMesa;
    private panelCartasPoker.PanelCartasPoker panelCartasPoker;
    private javax.swing.JTextArea taMensajes;
    private javax.swing.JTextField tfMontoApuesta;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void mostrarError(String message) {
        taMensajes.setText(message);
    }

    @Override
    public void mostrarTitulo(int numeroMesa, int numeroManoActual, String nombreCompleto, double saldoJugador) {
        String titulo = ("JUGADOR " + nombreCompleto.toUpperCase() + " - NUMERO DE MESA: " + numeroMesa + 
                " - NUMERO DE MANO ACTUAL: " + numeroManoActual + " - SALDO: " + saldoJugador);
        setTitle(titulo);
    }
    
    @Override
    public void mostrarJugadores(ArrayList<Jugador> listaJugadoresMesa){
        ArrayList<String> listadoJugadores = new ArrayList();
        for(Jugador j: listaJugadoresMesa){
            listadoJugadores.add("Nombre : " + j.getNombreCompleto() + " | Situación : " + j.getSituacion());
        }
        listaJugadoresEnMesa.setListData(listadoJugadores.toArray());
    }

    @Override
    public void mostrarFiguras(ArrayList<Figura> listaFiguras) {
        ArrayList<String> listadoFigurasPosibles = new ArrayList();
        for(Figura f: listaFiguras){
            listadoFigurasPosibles.add("Nombre : " + f.getNombre());
        }
        listaFigurasPosibles.setListData(listaFiguras.toArray());
    }

    @Override
    public void mostrarEstadoMano(String descripcion) {
        labelEstadoMano.setText("Estado de la mano: " + descripcion);
    }

    @Override
    public void cargarCartas(ArrayList<CartaPoker> cartas) {
        try {
            panelCartasPoker.cargarCartas(cartas);
        } catch (PanelCartasPokerException ex) {
            taMensajes.setText(ex.getMessage());
        }
    }

    @Override
    public void clickEnCarta(CartaPoker carta) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   @Override
    public void mostrarFiguraActual(Jugador j) {
        if (j.getLaFigura() != null) {
            labelFiguraActual.setText("Figura actual: " + j.getLaFigura().getNombre());
        } else {
            labelFiguraActual.setText("Figura actual: No disponible");
        }
    }

    @Override
    public void mostrarPozo(double pozo) {
        labelPozo.setText("Pozo: " + pozo);
    }

}
    
